<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-POGUVL90" failures="1" tests="2" name="Default test(failed)" time="0.266" errors="0" timestamp="2022-03-27T09:46:58 IST">
  <testcase classname="failedinTestNG.Failedclass1" name="TC2" time="0.222">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method failedinTestNG.Failedclass1.TC2() didn&amp;apos;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method failedinTestNG.Failedclass1.TC2() didn't finish within the time-out 200
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- TC2 -->
  <testcase classname="failedinTestNG.Failedclass1" name="TC3" time="0.004"/>
  <testcase classname="failedinTestNG.Failedclass1" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="failedinTestNG.Failedclass1" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
  <testcase classname="failedinTestNG.Failedclass1" name="TC5" time="0.0">
    <ignored/>
  </testcase> <!-- TC5 -->
</testsuite> <!-- Default test(failed) -->
