<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-POGUVL90" failures="0" tests="2" name="kiteAppTestClasses.kiteUserErrandPassErrMsg" time="0.569" errors="0" timestamp="2022-03-31T13:02:56 IST" skipped="0">
  <testcase classname="kiteAppTestClasses.kiteUserErrandPassErrMsg" name="validatePasswordErrorMsg" time="0.386"/>
  <system-out>
    <![CDATA[screenshot taken for TC 5
validate password error message ]]>
  </system-out>
  <testcase classname="kiteAppTestClasses.kiteUserErrandPassErrMsg" name="validateUserErrorMsg" time="0.183"/>
  <system-out>
    <![CDATA[screenshot taken for TC 4
Validate user error msg]]>
  </system-out>
</testsuite> <!-- kiteAppTestClasses.kiteUserErrandPassErrMsg -->
